version: '3.9'

services:
  frontend:
    build: .
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - perpustakaan-net

networks:
  perpustakaan-net:
    external: true
