version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"  # Vite dev server
    networks:
      - perpustakaan-net
    volumes:
      - .:/app   # live reload
      - /app/node_modules
    command: npm run dev

networks:
  perpustakaan-net:
    external: true
