version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: perpustakaan
    ports:
      - "3306:3306"
    networks:
      - perpustakaan-net

  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - perpustakaan-net

networks:
  perpustakaan-net:
    external: true
